sudo: required

language: java

services:
  - docker

jdk:
  - openjdk8

env:
  global:
    - secure: "ySadnYIRQEgElUa71s2q0pRPvSc9viTQ5WZ20Or1iJ9OdKqQtHDltPFw39V4hkpYfZho17drtMlKCPRNQZFh6SWcRhUGTLCWLrLrxfgjjRM77k/iEZwRx5vSdMiD+gqkCgVAW0iETAnTMF+cGiZqxSk9LnqKsVAaf+tlCi34FD0vs0OUKa4jP0+LPFrWxExQkKBJEALX7Cf67i3ALeUqfZ480XxooJO5Pq52qVlMza1mHUhsqXZCPYFpltlinAwjPop9dygR74BaAuBFdrC6FXACuMu3UnHfRBySQ1nY89V8yCRUuUsJ7YSQmH+oTm7Khu+NLpRzOwPBeQCOiEr+SacZ/ll4GfIsX28LJH4kCfVuZczDRcpRXZg48Fv1lNag1lLFFtJW3znTq3pk7GFNNLxOD7e52Hc4xRmjomyYXCp6u3xzk7m5/SH6Lf/+VOzs4oPNz2c0gisrJCZZ0qLCBqb53sRiq8BD+KoYpbtu+9odTLRmQc4SdJHyRfGkG3TYGvrX0G97E2vQoXk9siBXl4WhoG1QssaWXW7o2dRl+x+6WZtikOA6ATzr9EY6gGvhpdXpNTKJ6rl2dgMyvlLMx0etyLWTeoQuoyaBQLEGejtpUriG4hhA8EqzDhD2CoU6MakAIWmNoM96FwnNgu0pQh04+rdEuuncAHRyHc/glk0="
    - # ^^ COVERALLS_REPO_TOKEN
    - secure: "FHi4hNisAvxWvEJ0a3jp+jgJNjIcHPoFMAHzC6ExoWwyXwQzkwGmIqN2ibl8KbsnR7UowurzGoCtBx7zrF24mpxk7lJ8LSZ2Im74i9Hv03kHpRumcSlw2gCdlBiWeK4slenIxDPdrT4IvyplWoknlD8oQEChqUfk/dqQUdl84JHDy/ISXIl3UlRRe7zGaca7f5Xf1ehXlZxrc616fIP8IP1aWRU9Gg4QKCx8UeVU75Or+NFCDumxZ4ov5dxqzcOnEaOc5V153RqwTRnYhW457PJzC2H8/Dg4lA2x5sFf4oClEzjg5890QLTPJVybhFaNOIPGGF7p0mZGLRX6T9IdgrHcRBbiSrudoKvPf9HH+E6EhgKXrzuzvdCdhFhlqHMd6bYvOZSNBp4hcS00R8dqO1Olct0tr4Hb42e5PTOQ5Bsr8J2FVn2RhO0BcbFttL1dMbkGF2mSykTNiiq9fqM2EbfJ4kzO3/mTzCA89CHjqo/3zAHfWwbVS48zrxXZ19OjFLtLNvgYWJwkJCKWGXcixuYbOIMXvUM0MY0sGbgeUj3EAi8Y1UQvEelAx/74bY+bpjXQePOFt6w1Ihe64KcDrvTP/q+EzhmiY0myD0+IM/EG22JLB0uHN8EUYpZCOhGmKsLNlXmRPHKc/8jN7nzkH0UkMZLSg5UOEhu2NwC/p9A="
    - # ^^ DOCKER_USERNAME
    - secure: "OGvYAp0bi2BZSWut5+SkO/lf1cwk1yNQ5gCgummBApoln81EFT988wO1WP3dmd/ba8TDe3WBQn2uCUqFp8rJH7QgfyzDNcbdyLn3i7A2LQRIs1N8aagZW/lr2/7jnP5Vd4Bp9adWZ3u3ZmLkEqHX9DYxmVJnVFK2lXtlGzUjx0EcoiopSuzfWnQLQc2BD9yKtEupMPFOCL3VnHNf5wNIVPrK5JukyEO/dW98NRoYozFkq3YW2kN7LheT88hOB0rXVs4/MxJYkpvvyowS2nLwBL4ixDWdJnQkcNM5DATxQPMsA6dL5JUWUpWfzjQdOmWDOUJCDZhQdYR+vBdeWDCzOfsl3nUfx47cUggvn2MUGyaE9bE8IrLMsqwwFqhe9XB7YY/oiaWMyI2XS4Poq1kvClbmS/1+ky9WpsP/a8PorU1YqJFXxBGlK+ivlheroYF8oEEujC47UhywijPbMGaRSfJvJF65S2XQ/sSWYcjSWfVCsdRU4kKJNIfKK11bX+VR8JaPk38zCHftjbAgK/V/Jey8W3wOnDtKkz9QiEwqNB136hJvwpn6qx3oi/ICVfpH360hp4xgdyXCKKr+VjVNrXScCjquF6B8vwh8CRO7F7aFl1QwkMVNP0Yrd+o4lhFNazY0jIok6fx783jJiPHXHRBx/ceFS8mAgVAjfJdNcFY="
    - # ^^ DOCKER_PASSWORD
  matrix:
    secure: "x71UqiBBYIAbjLVVhOyVdCaEi3CdVIpgfJdAXrfYwl28ObSKsOnqG9Nl0A9D3nffgUYOztja02jHPeKJJk91GSSrgJ2utKxloVqvp26Spm9M8ZV5rRyyhOEDW67vfJ5MHseJlfPN3rojSQqtE3ax89M/C2DddeHz0pcAPh9OnMKdhtob0WnxXPF0N/LBzgE0heuuy4DshIvluEOVxogB9xUDCUBWNPDbwFP9bnxMh6glTBIXKhZxCCTjB5Jw/MmY1zlnxqq4lAb/kqExsKQjVH6a2dt3lysTLo/T1wuisWbYfiVmfVowFEhHaeO1CJkmqZR2XNwFEzrzbgDZSqICPB5MPGYOiEXymKdm8A2HNIvz4k7EJwre48XEmFWSFdAhf3UBwLbSRNWJPeTqvlDPrXzTj1Kdl0gcsaCQIzkLACWG16a+9oIMw//m4dFg9VY6MvqqWnBNBYPMRBF/EUcRiQsawLagOfuRMN88MSA1uOvkEXgwuvt3EzmGOVsn/FXdwr6tHr5wnnrnx/NhHOzbRG+iPIvd3RqObhfkoCaNnj/9mnIEb57CI0UDjnUyVi1ebnJn0dGRXWwLiSLjkN4/QATLKg2Cd+gkNQX5CSvj6HVT5YXBITeB19Yo7tCflu+kuyCwnAJ2FNHut6ZYaonS8AZqrz4PxOhJTDUv4DaDSaA="
    - # ^^ CODACY_PROJECT_TOKEN
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f app/pom.xml

script:
  - mvn test coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -B -f app/pom.xml

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r /app/target/site/jacoco.xml
  - docker build -t netshoes/athena-dependency-analyzer:1.0-SNAPSHOT -t netshoes/athena-dependency-analyzer:latest .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

cache:
  directories:
    - ~/.m2/repository